#!/bin/bash

if [ ! -d version ]; then
  mkdir version
fi

./scripts/config osp 4
cd run; make; cd ..
cp run/osp.pdf version/hallb-oper.pdf

./scripts/config osp 0
cd run; make; cd ..
cp run/osp.pdf version/hallb-esad.pdf


